### ISSUE TITLE
error in cor2cov(corX, sd = sqrt(2 * raf * (1 - raf)))

### ISSUE THREAD

**Issue by cthyshn** [jennasimit/MGflashfm#1]
hello, i hope my message finds you well!

i am interested in using mgflashfm for multi group, multi trait analysis (2 groups, 2 traits). however, i'm running into some issues that i'm not sure how to fix.

would you have any advice? thank you in advance

![image](https://github.com/jennasimit/MGflashfm/assets/70992350/821a7b11-d82d-4a39-9db1-104a577685c2)

**Comment by jennasimit** [comment]
Hello, 

I'm happy to help. Could you please double-check that your my.gwas.list has the same format as the example gwas.list within MGflashfm?  I have seen this error pop up before when there were mis-matches with the data format.

In your case of 2 traits and 2 groups, like the example, your my.gwas.list should be a list of two components, where my.gwas.list[[k]] is a list of two gwas data.frames for the two traits in group k (k=1,2). 

e.g. compare your my.gwas.list with the example data format:
lapply(gwas.list[[1]],head)
lapply(gwas.list[[2]],head)   

Hope this helps, but if you are still running into issues, please let me know.

**Comment by cthyshn** [comment]
thank you so much for your response! this is what gwas.list looks like compared to my.gwas.list:
![image](https://github.com/jennasimit/MGflashfm/assets/70992350/8a1baecf-9ccd-454a-a48a-784fb2625e5d)

i think that the data formats are the same? please let me know if i am missing something!

thanks!

**Comment by jennasimit** [comment]
Hi, 
Thanks for sharing this and sorry for the inconvenience. Yes, your gwas.list format looks fine. 

This might be easier for me to solve if you could send me your R objects (my.gwas.list, my.ld.list, my.cory.list, my.nall) by email (jennasimit@gmail.com). Then I could look at this more closely without asking you to run more checks. 

Thanks!

**Comment by jennasimit** [comment]
This has been fixed by email, but adding an update here for this issue log. 
Within the function, the LD matrix was recognised as a list instead of a matrix, even though it had matrix dimensions; it is now forced to be a matrix within the functions. Some error checks have also been added to make it easier to use. 
Please download and install the updated version.
