### ISSUE TITLE
error: only matrix diagonals can be replaced

### ISSUE THREAD

**Issue by cthyshn** [jennasimit/MGflashfm#2]
hello! sorry to bother you again! i'm running mgflashfm on a different dataset and i seem to be getting another error:

![image](https://github.com/jennasimit/MGflashfm/assets/70992350/761ce1c7-64f1-4de3-80bc-b4cb150d3f19)

any advice would be really appreciated!

thanks!

**Comment by jennasimit** [comment]
Hi Cathy,

Thanks for letting me know and apologies for this. My guess is that these
errors are coming up from a Windows machine?
I have made some changes to the code and have hopefully caught all
instances where there could be matrix issues (i.e. force an object to be a
matrix, even though it should already be one), but do let me know if there
are still issues.
So, please install again from github for this updated version.

Best wishes,
Jenn
