### ISSUE TITLE
MGfm no results.

### ISSUE THREAD

**Issue by ZikunY** [jennasimit/MGflashfm#4]
Hi Dr. Asimit,

  I am working on applying MGfm to simulated datasets, which is single trait with two ancestries (groups) scenario. However, basically, I got completely empty results from MGfm on all datasets. I assumed I might wrongfully use MGfm, but I do want to know how to get the PIPs of all the testing SNPs from MGfm, so that I could analyze the results to find out where I got it wrong. For now, MGfm only provided the information/results regarding the credible sets, which are empty. 

Thank you in advance. Your help would be greatly appreciated.

Best,
Zikun

**Comment by jennasimit** [comment]
Hi Zikun,

Thanks for your message. The details that you provided in the more recently raised issue have been helpful and I hope that my responses there have solved your issue. 

In this software, the PIPs are called mgMPP (multi-group Marginal Posterior Probability of inclusion), and they are detailed for all variants with mgMPP>0 in the output list component $CSdetail$details$mgMPP.

Best,
Jenn
