### ISSUE TITLE
Issue with JAM function parameters

### ISSUE THREAD

**Issue by ZikunY** [jennasimit/MGflashfm#6]
Hi Dr. Asimit,

 I tried to use MGflashfm on my local Mac, which worked well. My colleague and I found the reason that it didn't work on our cluster is due to "OpenJDK version 1.8.0" used on the cluster. Further, we found that Java is called by the package **R2BGLiMS**. The **R2BGLiMS::JAM** function has a parameter (**extra.java.arguments**) to pass the java arguments ([https://github.com/pjnewcombe/R2BGLiMS/blob/master/R/JAM.R].

When MGflashfm calls the R2BGLiMS::JAM function, it does not include the parameter "extra.java.arguments", as shown in the function calling in [https://github.com/jennasimit/MGflashfm/blob/master/R/flashfm-updated.R], line 23. 
 jam.results <- R2BGLiMS::JAM(marginal.betas = BETA, trait.variance = Vy,
            cor.ref = refG, mafs.ref = mafs.ref, model.space.priors = list(a = 1,
                b = length(BETA), Variables = names(BETA)), max.model.dim = maxcv,
            n = N, xtx.ridge.term = 0.01, save.path = save.path, n.mil.iter=jam.nM.iter)

The parameter "extra.java.arguments" is omitted in MGflashfm. To increase the java memory allocation for R2BGLiMS::JAM function, the parameter "extra.java.arguments" is needed to be added in "flashfm-updated.R". 

It would be greatly appreciated if the package could be updated to address this parameter. Such an update would significantly enhance the package's compatibility with various operating systems. Thank you for considering this request.

Best,
Zikun

**Comment by jennasimit** [comment]
Hi Zikun,

Thanks, this is a great suggestion! 

I have updated the package to include the "extra.java.arguments" in all functions that depend on R2BGLiMS::JAM.

I will also note here, that the functions have been updated so that the argument maxcv_autocheck is removed and maxcv_stop >= maxcv; previously the code was set up such that maxcv_stop > maxcv.

Best wishes,
Jenn
